/* Automatically generated by wasm2c */
#ifndef BOXES_H_GENERATED_
#define BOXES_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* import: 'wasi_snapshot_preview1' 'fd_write' */
extern u32 (*Z_wasi_snapshot_preview1Z_fd_write)(u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'environ_sizes_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_environ_sizes_get)(u32, u32);
/* import: 'wasi_snapshot_preview1' 'proc_exit' */
extern void (*Z_wasi_snapshot_preview1Z_proc_exit)(u32);
/* import: 'wasi_snapshot_preview1' 'environ_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_environ_get)(u32, u32);
void Z_boxes_init(void);
void Z_boxes_free(void);

/* export: 'memory' */
extern wasm_rt_memory_t (*Z_boxesZ_memory);
/* export: '__heap_base' */
extern u32 (*Z_boxesZ___heap_base);
/* export: '__data_end' */
extern u32 (*Z_boxesZ___data_end);
/* export: '_start' */
extern void (*Z_boxesZ__start)(void);
/* export: 'main' */
extern u32 (*Z_boxesZ_main)(u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* BOXES_H_GENERATED_ */
