
[package]
name = "sandboxed-box_unsafe_c"
version = "1.0.0+mswasm"
authors = ["generated-by-rwasm-1.0.0+mswasm"]
edition = "2018"

[dependencies]
wasi-common = "0.20.0"
wiggle = "0.20.0"


[profile.release]
debug = true


            